server:
  port: 8761
eureka:
  client:
    # 表示是否将自己注册到Eureka,因为要构建集群环境,需要将自己注册到集群,所以应该开启
    register-with-eureka: true
    # 表示是否从Eureka 获取注册信息,如果是单一节点,不需要同步其他Eureka节点,则可以设置为false,
    # 但此处为集群,应该设置为 true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.136:8761/eureka/,http://192.168.1.136:8771/eureka/,http://192.168.1.136:8781/eureka/