server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.136:8761/eureka/,http://192.168.1.136:8771/eureka/,http://192.168.1.136:8781/eureka/