server:
  port: 8762
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xvmingyuan/aispringclouddemo.git
          search-paths: config
          username: xvmingyuan
          password: xxxxxxxx
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/