server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    url: jdbc:mysql://localhost:3306/m?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

